"""Loads versioned prompt templates from disk.

Layout:
    app/prompts/v1/system.txt.j2
    app/prompts/v1/user.txt.j2
    app/prompts/v2/system.txt.j2
    app/prompts/v2/user.txt.j2

`load_prompt(version)` returns rendered system + user templates with the
LLMAnalysis JSON schema injected — keeping prompt and Pydantic model in sync.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape

from app.schemas.sentiment import LLMAnalysis

PROMPT_DIR = Path(__file__).resolve().parent


@dataclass(frozen=True, slots=True)
class PromptBundle:
    version: str
    system_template: str  # jinja source for system message
    user_template: (
        str  # jinja source for user message — expects {article_text, source_url, fetched_title}
    )

    def render_system(self) -> str:
        env = _env()
        tmpl = env.from_string(self.system_template)
        return tmpl.render(json_schema=_schema_for_prompt())

    def render_user(self, *, article_text: str, source_url: str, fetched_title: str | None) -> str:
        env = _env()
        tmpl = env.from_string(self.user_template)
        return tmpl.render(
            article_text=article_text,
            source_url=source_url,
            fetched_title=fetched_title or "(unknown)",
        )


@lru_cache(maxsize=8)
def load_prompt(version: str) -> PromptBundle:
    version_dir = PROMPT_DIR / version
    if not version_dir.is_dir():
        raise ValueError(f"Unknown prompt version: {version!r} (no directory at {version_dir})")

    system_path = version_dir / "system.txt.j2"
    user_path = version_dir / "user.txt.j2"
    if not system_path.exists() or not user_path.exists():
        raise ValueError(f"Prompt version {version!r} is missing system.txt.j2 or user.txt.j2")

    return PromptBundle(
        version=version,
        system_template=system_path.read_text(encoding="utf-8"),
        user_template=user_path.read_text(encoding="utf-8"),
    )


@lru_cache(maxsize=1)
def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(PROMPT_DIR),
        autoescape=select_autoescape(default=False),
        undefined=StrictUndefined,
        trim_blocks=False,
        lstrip_blocks=False,
        keep_trailing_newline=True,
    )


@lru_cache(maxsize=1)
def _schema_for_prompt() -> str:
    """Return the LLMAnalysis JSON schema, pretty-printed for prompt embedding."""
    schema = LLMAnalysis.model_json_schema()
    # Strip the noisy `title` autogenerated keys — they're not useful for the LLM.
    return json.dumps(schema, indent=2, sort_keys=False)
